# Generated by Django 5.2.8 on 2025-11-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('xray_image', models.ImageField(upload_to='xray_uploads/')),
                ('clinical_text', models.TextField()),
                ('predicted_class', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to='gradcam/')),
            ],
        ),
    ]
